- name: retrieve api_key
  hosts: palo
  gather_facts: no
  tasks:
    - name: get api key
      paloaltonetworks.panos.panos_api_key:
        provider: '{{ provider }}'
      register: auth

    - name: show api key
      debug:
        msg: '{{ auth.api_key }}'
